g++ `pkg-config --cflags glfw3` -o main main.cpp `pkg-config --static --libs glfw3`
g++ -I/usr/local/include main.cpp glad.c  -L/usr/local/lib -lglfw3 -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo -I .   && ./a.out
g++ -I/usr/local/include main.cpp glad.c  -L/usr/local/lib -lglfw3 -framework Cocoa -framework IOKit -framework CoreFoundation -framework CoreVideo -I .   && ./a.out
