triangle: triangle.cpp
	g++ `pkg-config --cflags glfw3` -o triangle triangle.cpp glad.c  `pkg-config --static --libs glfw3` -I .

hello-shaders: hello-shaders.cpp
	g++ `pkg-config --cflags glfw3` -o hello-shaders hello-shaders.cpp glad.c  `pkg-config --static --libs glfw3` -I .