triangle: triangle.cpp
	g++ `pkg-config --cflags glfw3` -o triangle triangle.cpp glad.c  `pkg-config --static --libs glfw3` -I .

shaders: shaders.cpp
	g++ `pkg-config --cflags glfw3` -o shaders shaders.cpp glad.c  `pkg-config --static --libs glfw3` -I .